using NetFwTypeLib;
using System;

namespace S5MS.Helpers
{
	class FirewallHelper
	{
		public static INetFwPolicy2 CurrentFirewallPolicy;
		public static INetFwRule CurrentFirewallOutRule;
		public static INetFwRule CurrentFirewallInRule;

		public static void Init()
		{
			CurrentFirewallPolicy = GetFirewallPolicy();
			CurrentFirewallOutRule = GenerateFirewallOutRule();
			CurrentFirewallInRule = GenerateFirewallInRule();

			RemoveCurrentRules();

			ConsoleHelper.OnExit += OnExit;
		}

		public static void OnExit()
		{
			RemoveCurrentRules();
		}

		public static void RemoveCurrentRules()
		{
			RemoveFirewallRule(CurrentFirewallOutRule);
			RemoveFirewallRule(CurrentFirewallInRule);
		}

		public static void AddFirewallRule(INetFwRule rule)
		{
			try
			{
				CurrentFirewallPolicy.Rules.Add(rule);
			}
			catch (Exception) { }
		}

		public static void RemoveFirewallRule(INetFwRule rule)
		{
			try
			{
				CurrentFirewallPolicy.Rules.Remove(rule.Name);
			}
			catch (Exception) { }
		}

		private static INetFwPolicy2 GetFirewallPolicy()
		{
			return (INetFwPolicy2)Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));
		}

		private static INetFwRule GenerateFirewallOutRule()
		{
			INetFwRule firewallRule = (INetFwRule)Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FWRule"));
			firewallRule.Name = "Steam5MinutesSharingGeneratedOutRule";
			firewallRule.Description = "This rule is generated by Steam5MinutesSharing.";
			firewallRule.ApplicationName = SteamHelper.CurrentSteamExecutablePath;
			firewallRule.Action = NET_FW_ACTION_.NET_FW_ACTION_BLOCK;
			firewallRule.Direction = NET_FW_RULE_DIRECTION_.NET_FW_RULE_DIR_OUT;
			firewallRule.InterfaceTypes = "All";
			firewallRule.Enabled = true;

			return firewallRule;
		}

		private static INetFwRule GenerateFirewallInRule()
		{
			INetFwRule firewallRule = (INetFwRule)Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FWRule"));
			firewallRule.Name = "Steam5MinutesSharingGeneratedInRule";
			firewallRule.Description = "This rule is generated by Steam5MinutesSharing.";
			firewallRule.ApplicationName = SteamHelper.CurrentSteamExecutablePath;
			firewallRule.Action = NET_FW_ACTION_.NET_FW_ACTION_BLOCK;
			firewallRule.Direction = NET_FW_RULE_DIRECTION_.NET_FW_RULE_DIR_IN;
			firewallRule.InterfaceTypes = "All";
			firewallRule.Enabled = true;

			return firewallRule;
		}
	}
}
